### PR TITLE
Add Roles in sign up form

### PR DESCRIPTION
**Pull request by LadySaturday**
Role based authorization

### CODE REVIEW

**Comment by youngmin1205** [comment]
Even I sign in, it keeps bring me to http://localhost:3000/unauthorized and ask me to sign in.
Screen Shot 2020-11-05 at 5 41 07 AM

**Comment by youngmin1205** [comment]
Is it working for you?

**Comment by youngmin1205** [comment]
It seems working when I sign up, but not working when I sign in with existing account

**Comment by youngmin1205** [comment]
Issue #22

**Comment by LadySaturday** [comment]
Yes, unfortunately all the accounts that were created before roles were implemented don't have a role, so the site will recognize them as a visitor. To keep an existing account, edit the user in MongoDb to add a role field.

**Pull request merged**
